--SCRIPCONFIGURATION
alter session set "_ORACLE_SCRIPT"=true; 
--Create tablespace
CREATE TABLESPACE TEACHERSRANKING DATAFILE 'E:\DataBases\Source\TeachersRanking\TEACHERSRANKING.DBF' SIZE 100M;
COMMIT;
--Create temporary tablespace
CREATE TEMPORARY TABLESPACE TEACHERSRANKINGTEMP TEMPFILE 'E:\DataBases\Source\TeachersRanking\TEACHERSRANKINGTEMP.DBF' SIZE 50M;
COMMIT;
--Create roles
CREATE ROLE TRankAdministrator;
COMMIT;
CREATE ROLE TRankCommon;
COMMIT;
CREATE ROLE TRankChecker;
COMMIT;
--Grant privilege
GRANT CONNECT, DBA, RESOURCE TO TRankAdministrator WITH ADMIN OPTION;
GRANT CONNECT, INSERT ANY TABLE, READ ANY TABLE, EXECUTE ANY PROCEDURE, SELECT ANY TABLE, UPDATE ANY TABLE, CREATE ANY VIEW TO TRankCommon;
GRANT CONNECT,INSERT ANY TABLE, DELETE ANY TABLE, READ ANY TABLE, EXECUTE ANY PROCEDURE, SELECT ANY TABLE, UPDATE ANY TABLE, CREATE ANY VIEW  TO TRankChecker;
--Create users
CREATE USER AdministratorUser IDENTIFIED BY admin DEFAULT TABLESPACE TEACHERSRANKING TEMPORARY TABLESPACE TEACHERSRANKINGTEMP QUOTA UNLIMITED ON TEACHERSRANKING;
COMMIT;
CREATE USER CommonUser IDENTIFIED BY root DEFAULT TABLESPACE TEACHERSRANKING TEMPORARY TABLESPACE TEACHERSRANKINGTEMP QUOTA UNLIMITED ON TEACHERSRANKING;
COMMIT;
CREATE USER CheckerUser IDENTIFIED BY root DEFAULT TABLESPACE TEACHERSRANKING TEMPORARY TABLESPACE TEACHERSRANKINGTEMP QUOTA UNLIMITED ON TEACHERSRANKING;
COMMIT;
--Assign role to user
GRANT TRankAdministrator TO AdministratorUser;
GRANT TRankCommon TO CommonUser;
GRANT TRankChecker TO CheckerUser;