--SchemaScrip
--Create sequences
CREATE SEQUENCE COMMON_USER_COMMON_USER_ID_SEQ
    INCREMENT BY 1
    START WITH 1000000000
    MAXVALUE 9999999999
    CACHE 10
    NOCYCLE;
CREATE SEQUENCE TEACHER_TEACHER_ID_SEQ
    INCREMENT BY 1
    START WITH 1000
    MAXVALUE 9999
    CACHE 10
    NOCYCLE;
CREATE SEQUENCE SEMESTER_LOG_SEMESTER_LOG_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    START WITH 1
    MAXVALUE 9999
    CACHE 10
    NOCYCLE;
CREATE SEQUENCE FACULTY_FACULTY_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    START WITH 1
    MAXVALUE 9
    NOCACHE
    NOCYCLE;
CREATE SEQUENCE REVIEW_REVIEW_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    START WITH 1
    MAXVALUE 9999999999
    CACHE 10
    NOCYCLE;
CREATE SEQUENCE SCORE_SCORE_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    START WITH 1
    MAXVALUE 9999999999
    CACHE 10
    NOCYCLE;
--Create tables with primary and foreign keys
CREATE TABLE TEACHER(
    TEACHER_ID NUMBER(4) DEFAULT TEACHER_TEACHER_ID_SEQ.NEXTVAL  CONSTRAINT TEACHER_TEACHER_ID_PK PRIMARY KEY CONSTRAINT TEACHER_TEACHER_ID_NN NOT NULL,
    FIRST_NAME VARCHAR2(20) CONSTRAINT TEACHER_FIRST_NAME_NN NOT NULL,
    SECOND_NAME VARCHAR2(20),
    FIRST_SURNAME VARCHAR2(20) CONSTRAINT TEACHER_FIRST_SURNAME_NN NOT NULL,
    SECOND_SURNAME VARCHAR2(20) CONSTRAINT TEACHER_SECOND_SURNAME_NN NOT NULL,
    IS_UPC_TEACHER NUMBER(1) DEFAULT 1 CONSTRAINT TEACHER_IS_UPC_TEACHER_NN NOT NULL CONSTRAINT TEACHER_IS_UPC_TEACHER_CK CHECK(IS_UPC_TEACHER = 1 OR IS_UPC_TEACHER = 0),
    STATUS NUMBER(1) DEFAULT 1 CONSTRAINT TEACHER_STATUS_NN NOT NULL CONSTRAINT TEACHER_STATUS_CK CHECK(STATUS = 1 OR STATUS = 0));
CREATE TABLE USER_TYPE(
    USER_TYPE_ID CHAR(1) CONSTRAINT USER_TYPE_USER_TYPE_ID_PK PRIMARY KEY CONSTRAINT USER_TYPE_USER_TYPE_ID_NN NOT NULL,
    DESCRIPTION VARCHAR2(20) CONSTRAINT USER_TYPE_DESCRIPTION_UK UNIQUE CONSTRAINT USER_TYPE_DESCRIPTION_NN NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 CONSTRAINT USER_TYPE_STATUS_NN NOT NULL CONSTRAINT USER_TYPE_STATUS_CK CHECK(STATUS = 1 OR STATUS = 0));
CREATE TABLE COMMON_USER(
    COMMON_USER_ID NUMBER(10) DEFAULT COMMON_USER_COMMON_USER_ID_SEQ.NEXTVAL CONSTRAINT COMMON_USER_COMMON_USER_ID_PK PRIMARY KEY CONSTRAINT COMMON_USER_COMMON_USER_ID_NN NOT NULL,
    FIRST_NAME VARCHAR2(20),
    SECOND_NAME VARCHAR2(20),
    FIRST_SURNAME VARCHAR2(20),
    SECOND_SURNAME VARCHAR2(20),
    EMAIL VARCHAR2(50) CONSTRAINT COMMON_USER_EMAIL_UK UNIQUE CONSTRAINT COMMON_USER_EMAIL_NN NOT NULL CONSTRAINT COMMON_USER_EMAIL_CK CHECK(EMAIL LIKE '%@%.%'),
    PASSWORD BLOB DEFAULT NULL,
    SALT BLOB DEFAULT NULL,
    IS_REGISTERED NUMBER(1) DEFAULT 0 CONSTRAINT COMMON_USER_IS_REGISTERED_NN NOT NULL CONSTRAINT COMMON_USER_IS_REGISTERED_CK CHECK(IS_REGISTERED = 1 OR IS_REGISTERED = 0),
    USER_TYPE  CHAR(1) DEFAULT '1' CONSTRAINT COMMON_USER_USER_TYPE_FK REFERENCES USER_TYPE(USER_TYPE_ID)CONSTRAINT COMMON_USER_USER_TYPE_NN NOT NULL);
CREATE TABLE FACULTY(
    FACULTY_ID NUMBER(1) DEFAULT FACULTY_FACULTY_ID_SEQ.NEXTVAL CONSTRAINT FACULTY_FACULTY_ID_PK PRIMARY KEY CONSTRAINT FACULTY_FACULTY_ID_NN NOT NULL,
    NAME VARCHAR2(100) CONSTRAINT FACULTY_NAME_UK UNIQUE CONSTRAINT FACULTY_NAME_NN NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 CONSTRAINT FACULTY_STATUS_NN NOT NULL CONSTRAINT FACULTY_STATUS_CK CHECK(STATUS = 1 OR STATUS = 0));
CREATE TABLE CAREER(
    CAREER_ID VARCHAR2(10) CONSTRAINT CAREER_CAREER_ID_PK PRIMARY KEY CONSTRAINT CAREER_CAREER_ID_NN NOT NULL,
    NAME VARCHAR2(100) CONSTRAINT CAREER_NAME_UK UNIQUE CONSTRAINT CAREER_NAME_NN NOT NULL,
    FACULTY_ID NUMBER(1) CONSTRAINT CAREER_FACULTY_ID_FK REFERENCES FACULTY(FACULTY_ID) CONSTRAINT CAREER_FACULTY_ID_NN NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 CONSTRAINT CAREER_STATUS_NN NOT NULL CONSTRAINT CAREER_STATUS_CK CHECK(STATUS = 1 OR STATUS = 0));
CREATE TABLE MATTER(
    MATTER_ID VARCHAR2(7) CONSTRAINT MATTER_MATTER_ID_PK PRIMARY KEY CONSTRAINT MATTER_MATTER_ID_NN NOT NULL,
    NAME VARCHAR2(100) CONSTRAINT MATTER_NAME_NN NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 CONSTRAINT MATTER_STATUS_NN NOT NULL CONSTRAINT MATTER_STATUS_CK CHECK(STATUS = 1 OR STATUS = 0));
CREATE TABLE SEMESTER_LOG(
    SEMESTER_LOG_ID NUMBER(4) DEFAULT SEMESTER_LOG_SEMESTER_LOG_ID_SEQ.NEXTVAL CONSTRAINT SEMESTERLOG_SEMESTER_ID_PK PRIMARY KEY CONSTRAINT SEMESTERLOG_SEMESTER_ID_NN NOT NULL,
    SEMESTER CHAR(1) CONSTRAINT SEMESTERLOG_SEMESTER_NN NOT NULL CONSTRAINT SEMESTERLOG_SEMESTER_CK CHECK(SEMESTER = 1 OR SEMESTER = 2),
    STARTDATE DATE CONSTRAINT SEMESTERLOG_STARTDATE_NN NOT NULL CONSTRAINT SEMESTERLOG_STARTDATE_UK UNIQUE,
    ENDDATE DATE CONSTRAINT SEMESTERLOG_ENDDATE_NN NOT NULL CONSTRAINT SEMESTERLOG_ENDDATE_UK UNIQUE,
    STATUS NUMBER(1) DEFAULT 1 CONSTRAINT SEMESTERLOG_STATUS_NN NOT NULL CONSTRAINT SEMESTERLOG_STATUS_CK CHECK(STATUS = 1 OR STATUS = 0));
CREATE TABLE R_CAREER_MATTER(
    CAREER_ID VARCHAR2(10) CONSTRAINT R_CAREER_MATTER_CAREER_ID_FK REFERENCES CAREER(CAREER_ID) CONSTRAINT R_CAREER_MATTER_CAREER_ID_NN NOT NULL,
    MATTER_ID VARCHAR2(7) CONSTRAINT R_CAREER_MATTER_MATTER_ID_FK REFERENCES MATTER(MATTER_ID) CONSTRAINT R_CAREER_MATTER_MATTER_ID_NN NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 CONSTRAINT R_CAREER_MATTER_STATUS_NN NOT NULL CONSTRAINT R_CAREER_MATTER_STATUS_CK CHECK(STATUS = 1 OR STATUS = 0),
    CONSTRAINT R_CAREER_MATTER_PK PRIMARY KEY (CAREER_ID, MATTER_ID));
CREATE TABLE R_TEACHER_MATTER(
    TEACHER_ID NUMBER(4) CONSTRAINT R_TEACHER_MATTER_TEACHER_ID_FK REFERENCES TEACHER(TEACHER_ID) CONSTRAINT R_TEACHER_MATTER_TEACHER_ID_NN NOT NULL,
    MATTER_ID VARCHAR2(7) CONSTRAINT R_TEACHER_MATTER_MATTER_ID_FK REFERENCES MATTER(MATTER_ID) CONSTRAINT R_TEACHER_MATTER_MATTER_ID_NN NOT NULL,
    SEMESTER_ID NUMBER(4) CONSTRAINT R_TEACHER_MATTER_SEMESTER_ID_FK REFERENCES SEMESTER_LOG(SEMESTER_LOG_ID) CONSTRAINT R_TEACHER_MATTER_SEMESTER_ID_NN NOT NULL CONSTRAINT R_TEACHER_MATTER_SEMESTER_ID_UK UNIQUE,
    STATUS NUMBER(1) DEFAULT 1 CONSTRAINT R_TEACHER_MATTER_STATUS_NN NOT NULL CONSTRAINT R_TEACHER_MATTER_STATUS_CK CHECK(STATUS = 1 OR STATUS = 0),
    CONSTRAINT R_TEACHER_MATTER_PK PRIMARY KEY (TEACHER_ID, MATTER_ID, SEMESTER_ID));
CREATE TABLE REVIEW(
    REVIEW_ID NUMBER(10) DEFAULT REVIEW_REVIEW_ID_SEQ.NEXTVAL CONSTRAINT REVIEW_REVIEW_ID_PK PRIMARY KEY CONSTRAINT REVIEW_REVIEW_ID_NN NOT NULL,
    TEACHER_ID NUMBER(4) CONSTRAINT REVIEW_TEACHER_ID_FK REFERENCES TEACHER(TEACHER_ID) CONSTRAINT REVIEW_TEACHER_ID_NN NOT NULL,
    COMMON_USER_ID NUMBER(10) CONSTRAINT REVIEW_COMMON_USER_ID_FK REFERENCES COMMON_USER(COMMON_USER_ID) CONSTRAINT REVIEW_COMMON_USER_ID_NN NOT NULL,
    MATTER_ID VARCHAR2(7) CONSTRAINT REVIEW_MATTER_ID_FK REFERENCES MATTER(MATTER_ID) CONSTRAINT REVIEW_MATTER_ID_NN NOT NULL,
    SEMESTER_ID NUMBER(4) CONSTRAINT REVIEW_SEMESTER_ID_FK REFERENCES SEMESTER_LOG(SEMESTER_LOG_ID) CONSTRAINT REVIEW_SEMESTER_ID_NN NOT NULL,
    CONTENT NCLOB,
    KNOWLEDGE NUMBER(1,0) CONSTRAINT REVIEW_KNOWLEDGE_NN NOT NULL CONSTRAINT REVIEW_KNOWLEDGE_CK CHECK(KNOWLEDGE BETWEEN 0 AND 5),
    METHODOLOGY NUMBER(1,0) CONSTRAINT REVIEW_METHODOLOGY_NN NOT NULL CONSTRAINT REVIEW_METHODOLOGY_CK CHECK(METHODOLOGY BETWEEN 0 AND 5),
    NATURALNESS NUMBER(1,0) CONSTRAINT REVIEW_NATURALNESS_NN NOT NULL CONSTRAINT REVIEW_NATURALNESS_CK CHECK(NATURALNESS BETWEEN 0 AND 5),
    ATTITUDE NUMBER(1,0) CONSTRAINT REVIEW_ATTITUDE_NN NOT NULL CONSTRAINT REVIEW_ATTITUDE_CK CHECK(ATTITUDE BETWEEN 0 AND 5),
    MOTIVATION_PRODUCE NUMBER(1,0) CONSTRAINT REVIEW_MOTIVATION_PRODUCE_NN NOT NULL CONSTRAINT REVIEW_MOTIVATION_PRODUCE_CK CHECK(MOTIVATION_PRODUCE BETWEEN 0 AND 5),
    MATTER_GUIDELINES NUMBER(1,0) CONSTRAINT REVIEW_MATTER_GUIDELINES_CK CHECK(MATTER_GUIDELINES BETWEEN 0 AND 5),
    WEIGHTED_AVERAGE NUMBER(3,2) CONSTRAINT REVIEW_WEIGHTED_AVERAGE_NN NOT NULL CONSTRAINT REVIEW_WEIGHTED_AVERAGE_CK CHECK(WEIGHTED_AVERAGE BETWEEN 0 AND 5),
    POST_DATE DATE DEFAULT SYSDATE CONSTRAINT REVIEW_POST_DATE_NN NOT NULL,
    IS_ANONYMOUS NUMBER(1) DEFAULT 0 CONSTRAINT REVIEW_IS_ANONYMOUS_NN NOT NULL CONSTRAINT REVIEW_IS_ANONYMOUS_CK CHECK(IS_ANONYMOUS = 1 OR IS_ANONYMOUS = 0),
    FAIL_ANY_MATTER NUMBER(1) DEFAULT 0 CONSTRAINT REVIEW_FAIL_ANY_MATTER_NN NOT NULL CONSTRAINT REVIEW_FAIL_ANY_MATTER_CK CHECK(FAIL_ANY_MATTER = 1 OR FAIL_ANY_MATTER = 0),
    STATUS NUMBER(1) DEFAULT 1 CONSTRAINT REVIEW_STATUS_NN NOT NULL CONSTRAINT REVIEW_STATUS_CK CHECK(STATUS = 1 OR STATUS = 0));
CREATE TABLE SCORE(
    SCORE_ID NUMBER(10) DEFAULT SCORE_SCORE_ID_SEQ.NEXTVAL CONSTRAINT SCORE_SCORE_ID_PK PRIMARY KEY CONSTRAINT SCORE_SCORE_ID_NN NOT NULL,
    TEACHER_ID NUMBER(4) CONSTRAINT SCORE_TEACHER_ID_FK REFERENCES TEACHER(TEACHER_ID) CONSTRAINT SCORE_TEACHER_ID_NN NOT NULL,
    SEMESTER_ID NUMBER(4) CONSTRAINT SCORE_SEMESTER_ID_FK REFERENCES SEMESTER_LOG(SEMESTER_LOG_ID) CONSTRAINT SCORE_SEMESTER_ID_NN NOT NULL CONSTRAINT SCORE_SEMESTER_ID_UK UNIQUE,
    KNOWLEDGE NUMBER(3,2) CONSTRAINT SCORE_KNOWLEDGE_NN NOT NULL CONSTRAINT SCORE_KNOWLEDGE_CK CHECK(KNOWLEDGE BETWEEN 0 AND 5),
    METHODOLOGY NUMBER(3,2) CONSTRAINT SCORE_METHODOLOGY_NN NOT NULL CONSTRAINT SCORE_METHODOLOGY_CK CHECK(METHODOLOGY BETWEEN 0 AND 5),
    NATURALNESS NUMBER(3,2) CONSTRAINT SCORE_NATURALNESS_NN NOT NULL CONSTRAINT SCORE_NATURALNESS_CK CHECK(NATURALNESS BETWEEN 0 AND 5),
    ATTITUDE NUMBER(3,2) CONSTRAINT SCORE_ATTITUDE_NN NOT NULL CONSTRAINT SCORE_ATTITUDE_CK CHECK(ATTITUDE BETWEEN 0 AND 5),
    MOTIVATION_PRODUCE NUMBER(3,2) CONSTRAINT SCORE_MOTIVATION_PRODUCE_NN NOT NULL CONSTRAINT SCORE_MOTIVATION_PRODUCE_CK CHECK(MOTIVATION_PRODUCE BETWEEN 0 AND 5),
    MATTER_GUIDELINES NUMBER(3,2) CONSTRAINT SCORE_MATTER_GUIDELINES_CK CHECK(MATTER_GUIDELINES BETWEEN 0 AND 5),
    FINAL_SCORE NUMBER(3,2) DEFAULT 0 CONSTRAINT SCORE_FINAL_SCORE_ID_NN NOT NULL,
    TOTAL_REVIEWS NUMBER(10) CONSTRAINT SCORE_TOTAL_REVIEWS_NN NOT NULL);